name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust stable
      uses: action-rs/toolchain@v1
      with:
        toolchain: stable
      
    - name: Build project
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

    - name: Check formating
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings
